pipeline:
  name: qqq
  identifier: qqq
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: plan
        identifier: plan
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: solugenix
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.terraform_git
                    repoName: terraform-zero-to-hero
                    build:
                      type: branch
                      spec:
                        branch: main
        tags: {}
    - stage:
        name: qq
        identifier: qq
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: solugenix
          execution:
            steps:
              - parallel:
                  - step:
                      type: IACMTerraformPlugin
                      name: init
                      identifier: init
                      timeout: 10m
                      spec:
                        command: init
                  - step:
                      type: GitClone
                      name: GitClone_1
                      identifier: GitClone_1
                      spec:
                        connectorRef: account.terraform_git
                        repoName: terraform-zero-to-hero
                        build:
                          type: branch
                          spec:
                            branch: main
                      description: jfjh
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
        tags: {}
